### ISSUE TITLE
Setup development environment

### ISSUE THREAD

**Issue by Omotoke244** [CSCI-GA-2820-SP23-001/customers#1]
**As a** developer
**I need** the development environment to be running
**So that** I can build the customer microservice
   
 ### Details and Assumptions
Development environment will run in VScode
   
 ### Acceptance Criteria  
   
 ```gherkin
Open container in VS code environment successfully

**Comment by ep2884** [comment]
@Omotoke244 Remember to complete the body of this issue before we submit HW#1 tonight

**Comment by Omotoke244** [comment]
Completed @ep2884

**Comment by Mahak3191** [comment]
This story has been completed since the development environment was already set up in advance.
