### ISSUE TITLE
Create a Kubernetes Cluster in IBM Cloud

### ISSUE THREAD

**Issue by ep2884** [CSCI-GA-2820-SP23-001/customers#51]
As a Developer
I need a Kubernetes cluster on IBM cloud
So that cloud deployment can be completed

Acceptance Criteria
IBM cloud works

**Comment by Sugiyaro** [comment]
Dude cloud not easy cmon.. can blow my brain lol the hell

**Comment by Sugiz** [comment]
Im not script and code what can u do that 🌊
