### ISSUE TITLE
[Delete] Delete existing customers

### ISSUE THREAD

**Issue by Mahak3191** [CSCI-GA-2820-SP23-001/customers#8]
**As a** account manager
**I need** to be able to delete customers
**So that**  if a customer does not wish to continue their account or if there is a problem/ default at the customer level or if there is a scam/ fake customer account, it can be deleted and removed from the existing customer accounts
   
 ### Details and Assumptions
 *  the DB exists as a PostgreSQL DB
 * if delete to a non-existing entry is issued, the API will return entry not found and the consuming layer will handle the exception
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given that a customer account needs to be deleted 
 When the account manager gives a command to delete it
 Then the customer account in question is removed from the list of customer accounts and does not show up in list or get i.e. it is removed from the database.```

**Comment by sgp9468** [comment]
3/16 - Updated routes.py & test_routes.py for delete-customer story. Confirmed the test passed.

Test Cases for Customer Model
Test creating customer record
delete customer
Test updating customer record
